
services:
  db:
    image: postgres:17
    container_name: postgres_auth
    environment:
      POSTGRES_DB: authentification
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_auth
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=authentification
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
